install:
  - ps: Install-Product node 5
  - npm install

test_script:
  - node --version
  - npm --version
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

build: off
version: "{build}"
